# Generated by Django 5.1.7 on 2025-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='47f2183091ae0c471122a834372a7ba29b478b923bc3b8f83c43db86ad725e65', max_length=100, unique=True),
        ),
    ]
