# Generated by Django 5.1.7 on 2025-03-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_app_secret_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_secret_token',
            field=models.CharField(default='f55302ec999a46dd621d956f95ae704f6d0f7d0e4fbf572ab619d60b2868f87e', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='processed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
